### ISSUE TITLE
Error in bundling @celo/identity into a new package

### ISSUE THREAD

**Issue by viral-sangani** [celo-org/social-connect#145]
### What I am trying to achieve

Hello Team,

I am currently working on a wrapper package around `@celo/identity` and `next-auth` named `react-socialconnect`. The main aim of this package is to simplify the boilerplate code and provide a seamless interface for server-side calls like `registerIdentifier`, `revokeIdentifier`, and `lookup`. The project repository can be found at [react-socialconnect](https://github.com/celo-org/react-socialconnect).

While not utilizing any bundler (though attempted both webpack and parcel, facing errors during bundling), I am encountering an issue when attempting to use the package in a Next.js API. Below is a simplified version of how I envision the usage of react-socialconnect in a Next.js API:

```js
const issuer = new SocialConnectIssuer(wallet, {
        authenticationMethod: AuthenticationMethod.ENCRYPTION_KEY,
        rawKey: process.env.DEK_PRIVATE_KEY as string,
});

await issuer.lookup(
        identifier,
        identifierType,
        issuerAddresses
);
await issuer.registerOnChainIdentifier(
        identifier,
        identifierType,
        account as string
      );
await issuer.deregisterOnChainIdentifier(
        identifier,
        identifierType,
        account as string
      );
```

When attempting the above, I encounter the following error:

```text
⨯ Error: Cannot find module 'util'
    at webpackEmptyContext (/Users/viral-sangani/Desktop/Project/react-socialconnect-temp/.next/server/pages/api/socialconnect/lookup.js:22:10)
    at eval (webpack-internal:///(api)/../react-socialconnect/node_modules/@celo/identity/node_modules/blind-threshold-bls/src/blind_threshold_bls.js:4:174)
    at (api)/../react-socialconnect/node_modules/@celo/identity/node_modules/blind-threshold-bls/src/blind_threshold_bls.js (/Users/viral-sangani/Desktop/Project/react-socialconnect-temp/.next/server/vendor-chunks/@celo.js:2611:1)
    at __webpack_require__ (/Users/viral-sangani/Desktop/Project/react-socialconnect-temp/.next/server/webpack-api-runtime.js:33:43)
    at new WasmBlsBlindingClient (webpack-internal:///(api)/../react-socialconnect/node_modules/@celo/identity/lib/odis/bls-blinding-client.js:29:33)
    at Object.eval (webpack-internal:///(api)/../react-socialconnect/node_modules/@celo/identity/lib/odis/identifier.js:62:33)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///(api)/../react-socialconnect/node_modules/@celo/identity/lib/odis/identifier.js:8:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(api)/../react-socialconnect/node_modules/@celo/identity/lib/odis/identifier.js:4:12)
    at Object.getObfuscatedIdentifier (webpack-internal:///(api)/../react-socialconnect/node_modules/@celo/identity/lib/odis/identifier.js:50:12)
    at SocialConnectIssuer.getObfuscatedId (webpack-internal:///(api)/../react-socialconnect/dist/SocialConnect/index.js:51:113)
    at SocialConnectIssuer.lookup (webpack-internal:///(api)/../react-socialconnect/dist/SocialConnect/index.js:95:41)
    at lookup (webpack-internal:///(api)/./pages/api/socialconnect/lookup.ts:40:47)
    at /Users/viral-sangani/Desktop/Project/react-socialconnect-temp/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3039
    at /Users/viral-sangani/Desktop/Project/react-socialconnect-temp/node_modules/next/dist/server/lib/trace/tracer.js:121:36
    at NoopContextManager.with (/Users/viral-sangani/Desktop/Project/react-socialconnect-temp/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
    at ContextAPI.with (/Users/viral-sangani/Desktop/Project/react-socialconnect-temp/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at NoopTracer.startActiveSpan (/Users/viral-sangani/Desktop/Project/react-socialconnect-temp/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
    at ProxyTracer.startActiveSpan (/Users/viral-sangani/Desktop/Project/react-socialconnect-temp/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
    at /Users/viral-sangani/Desktop/Project/react-socialconnect-temp/node_modules/next/dist/server/lib/trace/tracer.js:110:107
    at NoopContextManager.with (/Users/viral-sangani/Desktop/Project/react-socialconnect-temp/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
    at ContextAPI.with (/Users/viral-sangani/Desktop/Project/react-socialconnect-temp/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at NextTracerImpl.trace (/Users/viral-sangani/Desktop/Project/react-socialconnect-temp/node_modules/next/dist/server/lib/trace/tracer.js:110:32)
    at K (/Users/viral-sangani/Desktop/Project/react-socialconnect-temp/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2970)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async U.render (/Users/viral-sangani/Desktop/Project/react-socialconnect-temp/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3827) {
  code: 'MODULE_NOT_FOUND',
  page: '/api/socialconnect/lookup'
}
```

Additionally, there's a warning related to the usage of Buffer():

```
(node:61475) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

> Note: The `react-socialconnect` code functions as expected when integrated directly into a project by copying and pasting the entire package folder. However, the issues arise when attempting to utilize the code via the package installation. This leads to a probable conclusion that the problem might be associated with the packaging or bundling process.

cc @0xarthurxyz

**Comment by Ronexlemon** [comment]
getting the same error any leads?

**Comment by 0xarthurxyz** [comment]
@viral-sangani: This sounds like this problem for which a workaround has been documented in the GitHub discussion.
- https://github.com/celo-org/SocialConnect/discussions/3
